print('hi')

'''
Traceback (most recent call last): File "C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/runpy.py", line 193, in _run_module_as_main "main", mod_spec) File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/runpy.py", line 85, in _run_code exec(code, run_globals) File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/site-packages/ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/site-packages/ipykernel__init__.py", line 2, in from .connect import File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/site-packages/ipykernel/connect.py", line 18, in import jupyter_client File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/site-packages/jupyter_client__init__.py", line 4, in from .connect import File

"C:/Users/ympai/scoop/apps/anaconda3/current/envs/jupyter/lib/site-packages/jupyter_client/connect.py", line 23, in import zmq ModuleNotFoundError: No module named 'zmq'
'''
